// Generated by https://quicktype.io

export interface Patient {
    pkUserId:      number;
    fkRoleId:      number;
    username:      string;
    password:      string;
    firstName:     string;
    lastName:      string;
    age:           number;
    pkPatientId:   number;
    patientHeight: number;
    patientWeight: number;
    street:        string;
    city:          string;
    doorNo:        string;
    bloodGroup:    string;
}
